package models

type SheetName string

const (
	SheetGeneralRules              SheetName = "GENERAL RULES"
	SheetBODIES                    SheetName = "BODIES"
	SheetTAILS                     SheetName = "TAILS"
	SheetELVENEAR                  SheetName = "ELVEN EAR"
	SheetDROPLETS                  SheetName = "DROPLETS"
	SheetHANDS                     SheetName = "HANDS"
	SheetHAIR                      SheetName = "HAIR"
	SheetHATS                      SheetName = "HATS"
	SheetSTACKABLEHATS             SheetName = "STACKABLE HATS"
	SheetMOUTH                     SheetName = "MOUTH"
	SheetNOSE                      SheetName = "NOSE"
	SheetEYES                      SheetName = "EYES"
	SheetGLASSES                   SheetName = "GLASSES"
	SheetEARRINGS                  SheetName = "EARRINGS"
	SheetCLOTHES                   SheetName = "CLOTHES"
	SheetWINGS                     SheetName = "WINGS"
	SheetWEAPONS                   SheetName = "WEAPONS"
	SheetFACEGEARS                 SheetName = "FACE GEAR"
	SheetBG                        SheetName = "BG"
	SheetBGACCENTS                 SheetName = "BG ACCENT"
	SheetAURA                      SheetName = "AURA"
	SheetDEFAULTMaleCLOTHES        SheetName = "MALE DEFAULT CLOTHES"
	SheetDEFAULTFemaleCLOTHES      SheetName = "FEMALE DEFAULT CLOTHES"
	SheetDEFAULTMaleMOUTHS         SheetName = "MALE DEFAULT MOUTHS"
	SheetDEFAULTFemaleMOUTHS       SheetName = "FEMALE DEFAULT MOUTHS"
	SheetDEFAULTMaleEYES           SheetName = "MALE DEFAULT EYES"
	SheetDEFAULTFemaleEYES         SheetName = "FEMALE DEFAULT EYES"
	SheetDEFAULTMaleHAIR           SheetName = "MALE DEFAULT HAIR"
	SheetDEFAULTFemaleHAIR         SheetName = "FEMALE DEFAULT HAIR"
	SheetDEFAULTMaleHATS           SheetName = "MALE DEFAULT HAT"
	SheetDEFAULTFemaleHATS         SheetName = "FEMALE DEFAULT HAT"
	SheetMALEDEFAULTSTACKABLEHAT   SheetName = "MALE DEFAULT STACKABLE HAT"
	SheetFEMALEDEFAULTSTACKABLEHAT SheetName = "FEMALE DEFAULT STACKABLE HAT"
)
